name: Main workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check_config:
    runs-on: [self-hosted, nuc8beh]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: ls
